import './globals.css'
import { Inter } from 'next/font/google'
import Search from './search'

const inter = Inter({ subsets: ['latin'] })
// import MyState from './MyState.js'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en">

      <body className={inter.className} suppressHydrationWarning={true}>
      <Search/>
        {children}
        </body>
  
    </html>
  )
}
